#runtime: python
#env: flex
#entrypoint: gunicorn -b :$PORT main:app
#
#runtime_config:
#    python_version: 3

runtime: python37
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
